#
# Test: A08
#
# 1. Execute ../../util/acgen.jl act.toml.
# 2. Change solver = "MaxEnt" and the [Solver] block.
# 3. Execute ../../util/acflow.jl act.toml.
# 4. Execute ../../util/acplot.jl act.toml.
# 5. Change ptype = "random2" and repeat the above steps.
#

[Test]
solver = "MaxEnt"
ptype  = "random1"
ktype  = "fermi"
grid   = "ftime"
mesh   = "linear"
ngrid  = 257
nmesh  = 801
ntest  = 2000
nbins  = 100
wmax   = 8.0
wmin   = -8.0
pmax   = 4.0
pmin   = -4.0
beta   = 20.0
noise  = 1.0e-6
lcorr  = 0.5
tcorr  = true
fnpd   = false
fpbc   = false
lpeak  = [1,2,3,4,5,6]
