#
# dataset: mat_bsymm_cont_n1e-5
#
# code: ACTest v1.2.0-devel.250716
#

[Test]
solver = "MaxEnt"
ptype  = "random1"
ktype  = "bsymm"
grid   = "bfreq"
mesh   = "linear"
ngrid  = 200
nmesh  = 801
ntest  = 10000
nbins  = 1
wmax   = 8.0
wmin   = 0.0
pmax   = 4.0
pmin   = 0.0
beta   = 20.0
noise  = 1.0e-5
lcorr  = 0.5
tcorr  = false
fnpd   = false
fpbc   = false
lpeak  = [1,2,3,4,5,6]
